version: '3'
services:
  web:
    image: php:7.2-apache
    volumes:
      - ./:/var/www/html/
    ports:
      - "8080:80"
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: myDB
      MYSQL_USER: username
      MYSQL_PASSWORD: password
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    ports:
      - '8081:80'
    environment:
      PMA_HOST: db
      PMA_USER: username
      PMA_PASSWORD: password
      PMA_ARBITRARY: 1
volumes:
  db_data:
